menu:
    Blog: /
    Archive: /archives/
    About: /about/
    GitHub: https://github.com/zengxs
    Rss: /atom.xml

favicon: /favicon.ico
logo: /avatar.jpg

# Comment
# e.g disqus: seansun
disqus: zengxs
duoshuo:

# Analytics
# google-analytics:
# ga: UA-65933410-1

# Copyright Infomation
startyear: 2018
